name: Singularity Build (docker)
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        singularity_version:
          - '3.5.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config \
          python-dev python python3-pip

    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Build Container
      env:
        SINGULARITY_RECIPE: Singularity
        OUTPUT_CONTAINER: container.sif
      run: |
       ls
       if [ -f "${SINGULARITY_RECIPE}" ]; then
           singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
       else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
           ls
       fi
  - name: Test Container
      run: |
        singularity exec smokey.sif python run_tests.py
        singularity test smokey.sif
        singularity run toasty.sif
    - name: Deploy Container
      run: |
        sudo pip3 install sregistry
        SREGISTRY_CLIENT=registry sregistry push --name adamwilson/geospatial_plus geospatial_plus.sif
